### ISSUE TITLE
crash upon sand falling down, while using other GC addons (together with amunra)

### ISSUE THREAD

**Issue by DeLourium** [katzenpapst/amunra#1]
so as the title already says: im using Galacticraft along with extraplanets, galaxyspace and amunra (and made sure to remove duplicate planets), to test things out, i went to jupiter generated by extraplanets and after placing sand and made it fall down, my client crashed. The crash log states that there was a ticking entity (i guess the falling sand) and the mod amun-ra is listed sometimes (no other mods):Caused by: java.lang.NullPointerException
    at de.katzenpapst.amunra.block.ore.SubBlockOre.func_149692_a(SubBlockOre.java:111)

And here is the whole crashlog:
Minecraft Crash Report ----
// Who set us up the TNT?

Time: 6/24/16 5:20 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
    at de.katzenpapst.amunra.block.ore.SubBlockOre.func_149692_a(SubBlockOre.java:111)
    at de.katzenpapst.amunra.block.BlockBasicMeta.func_149692_a(BlockBasicMeta.java:215)
    at net.minecraft.entity.item.EntityFallingBlock.func_70071_h_(SourceFile:139)
    at net.minecraft.world.World.func_72866_a(World.java:2070)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
    at net.minecraft.world.World.func_72870_g(World.java:2034)
    at net.minecraft.world.World.func_72939_s(World.java:1887)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at de.katzenpapst.amunra.block.ore.SubBlockOre.func_149692_a(SubBlockOre.java:111)
    at de.katzenpapst.amunra.block.BlockBasicMeta.func_149692_a(BlockBasicMeta.java:215)
    at net.minecraft.entity.item.EntityFallingBlock.func_70071_h_(SourceFile:139)
    at net.minecraft.world.World.func_72866_a(World.java:2070)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
    at net.minecraft.world.World.func_72870_g(World.java:2034)

-- Entity being ticked --
Details:
    Entity Type: FallingSand (net.minecraft.entity.item.EntityFallingBlock)
    Entity ID: 207746
    Entity Name: Falling Block
    Entity's Exact location: -276.15, 62.49, 520.43
    Entity's Block location: World: (-277,62,520), Chunk: (at 11,3,8 in -18,32; contains blocks -288,0,512 to -273,255,527), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
    Entity's Momentum: -0.07, -0.00, 0.03
    Immitating block ID: 560
    Immitating block data: 9
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1887)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
    Level name: New World
    All players: 1 total; [GCEntityPlayerMP['Sir_Ludicrous'/530, l='New World', x=-45.30, y=70.00, z=707.92]]
    Chunk stats: ServerChunkCache: 1226 Drop: 0
    Level seed: -531056123581944568
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 0 game time, 0 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: ~~ERROR~~ NullPointerException: null
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_73, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1166669768 bytes (1112 MB) / 5992611840 bytes (5715 MB) up to 7158628352 bytes (6827 MB)
    JVM Flags: 3 total; -Xms256M -Xmx7680M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 247 mods loaded, 247 mods active

**Comment by katzenpapst** [comment]
WTF. What block is Block ID 560 in your setup? Almost looks like one of my ores generated on your Jupiter and broke.

**Comment by DeLourium** [comment]
Small Bone segment by biomes´o´plenty (has different nbt values for different sizes). fortunately this crash only occured once ^^ (eventhough i´ve removed extra planets now due to some other wierd stuff)

**Comment by katzenpapst** [comment]
Oh well, since this hasn't happened since then, I'll just close it
