### ISSUE TITLE
Crash with non-shuttle rockets launching off Motherships

### ISSUE THREAD

**Issue by katzenpapst** [katzenpapst/amunra#2]
java.lang.NullPointerException: Ticking entity
at micdoodle8.mods.galacticraft.core.util.WorldUtil.getPossibleDimensionsForSpaceshipTier(WorldUtil.java:459)
at micdoodle8.mods.galacticraft.core.util.WorldUtil.getArrayOfPossibleDimensions(WorldUtil.java:574)
at micdoodle8.mods.galacticraft.core.util.WorldUtil.toCelestialSelection(WorldUtil.java:1622)
at micdoodle8.mods.galacticraft.api.prefab.entity.EntityTieredRocket.onReachAtmosphere(EntityTieredRocket.java:426)
at micdoodle8.mods.galacticraft.api.prefab.entity.EntitySpaceshipBase.func_70071_h_(EntitySpaceshipBase.java:231)
at micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket.func_70071_h_(EntityAutoRocket.java:335)
at micdoodle8.mods.galacticraft.api.prefab.entity.EntityTieredRocket.func_70071_h_(EntityTieredRocket.java:203)
at micdoodle8.mods.galacticraft.planets.asteroids.entities.EntityTier3Rocket.func_70071_h_(EntityTier3Rocket.java:78)
at net.minecraft.world.World.func_72866_a(World.java:2070)
at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
at net.minecraft.world.World.func_72870_g(World.java:2034)
at net.minecraft.world.World.func_72939_s(World.java:1887)
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by katzenpapst** [comment]
Crash occurs if at least one space station is present. Motherships having no SpaceStationData is the problem.
